version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_CLEANUP=false
      - DOCKER_API_VERSION=1.42
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_MONITOR_ONLY=false
      # WATCHTOWER_NOTIFICATION_URL is in private.env
    env_file:
      - /opt/docker/watchtower/private.env
    restart: unless-stopped
